---
- name: Enable Dock auto-hide
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: boolean
    value: true
    state: present

- name: Speed up auto hide
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 0.3
    state: present

- name: Disable auto hide delay
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
    state: present
