---
# tasks file for dronenb.macos-defaults

- name: Get list of users on machine with home directories
  ansible.builtin.find:
    paths: /Users
    file_type: directory
    excludes: "Shared,root"
  register: users

- name: User specific tasks
  include_tasks: user_specific.yml
  loop: "{{ users.files }}"
  vars:
    - become_username: "{{ item.path | basename }}"
