---
# tasks file for dronenb.macos-defaults

- name: Get list of users on machine with home directories
  ansible.builtin.find:
    paths: /Users
    file_type: directory
    excludes: "Shared,root"
  register: users

# DOCK
- block:
  - name: Enable Dock auto-hide
    community.general.osx_defaults:
      domain: com.apple.dock
      key: autohide
      type: boolean
      value: true
      state: present

  - name: Speed up auto hide
    community.general.osx_defaults:
      domain: com.apple.dock
      key: autohide-time-modifier
      type: float
      value: 0.3
      state: present

  - name: Disable auto hide delay
    community.general.osx_defaults:
      domain: com.apple.dock
      key: autohide-delay
      type: float
      value: 0
      state: present

  - name: Enable always show scroll bars
    community.general.osx_defaults:
      domain: NSGlobalDomain
      key: AppleShowScrollBars
      type: string
      value: "Always"

# MENU BAR
- block:
  - name: Enable battery percentage
    loop: "{{ users.files }}"
    community.general.osx_defaults:
      domain: "{{ item.path }}/Library/Preferences/ByHost/com.apple.controlcenter.plist"
      key: BatteryShowPercentage
      type: boolean
      value: true
  
  - name: Enable Bluetooth icon in menu bar
    loop: "{{ users.files }}"
    community.general.osx_defaults:
      domain: "{{ item.path }}/Library/Preferences/ByHost/com.apple.controlcenter.plist"
      key: Bluetooth
      type: int
      value: 18
      state: present


# MOUSE
- block:
  # TODO:   This only works after logout/login. There seems to be a way to not have to though:
  #           https://shadowfacts.net/2021/scrollswitcher/
  #           https://github.com/pilotmoon/Scroll-Reverser
  - name: Disable natural scrolling
    community.general.osx_defaults:
      domain: NSGlobalDomain
      key: com.apple.swipescrolldirection
      type: int
      value: 0
      state: present

  - name: Enable right click (1)
    community.general.osx_defaults:
      domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
      key: TrackpadCornerSecondaryClick
      type: int
      value: 2

  - name: Enable right click (1)
    community.general.osx_defaults:
      domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
      key: TrackpadRightClick
      type: int
      value: 0

  - name: Enable tap to click
    community.general.osx_defaults:
      domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
      key: Clicking
      type: int
      value: 1

# FINDER
- block:
  - name: Show filename extensions
    community.general.osx_defaults:
      domain: NSGlobalDomain
      key: AppleShowAllExtensions
      type: boolean
      value: true

  - name: Don't create .DS_Store files on network volumes
    community.general.osx_defaults:
      domain: com.apple.desktopservices
      key: DSDontWriteNetworkStores
      type: boolean
      value: true

  - name: Don't create .DS_Store files on USB volumes
    community.general.osx_defaults:
      domain: com.apple.desktopservices
      key: DSDontWriteUSBStores
      type: boolean
      value: true

  - name: Enable AirDrop over ethernet
    community.general.osx_defaults:
      domain: com.apple.NetworkBrowser
      key: BrowseAllInterfaces
      type: boolean
      value: true

  - name: Enable AirDrop over ethernet
    community.general.osx_defaults:
      domain: org.gpgtools.common
      key: UseKeychain
      type: boolean
      value: true

# TERMINAL
- block:
  - name: Enable focus follows mouse for Terminal
    community.general.osx_defaults:
      domain: com.apple.terminal
      key: FocusFollowsMouse
      type: boolean
      value: true
