---
- name: Disable natural scrolling
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: int
    value: 0
    state: present

- name: Enable right click (1)
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2

- name: Enable right click (2)
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: int
    value: 0

- name: Enable tap to click
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 1

- name: Enable focus follows mouse for Terminal
  community.general.osx_defaults:
    domain: com.apple.terminal
    key: FocusFollowsMouse
    type: boolean
    value: true

- name: Enable always show scroll bars
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: "Always"
