---
- name: Block of user specific items
  become: true
  become_user: "{{ become_username }}"
  block:
    - name: Dock related items
      ansible.builtin.include_tasks: dock.yml

    - name: Menu Bar related items
      ansible.builtin.include_tasks: menu_bar.yml

    - name: Finder related items
      ansible.builtin.include_tasks: finder.yml

    - name: Random other
      ansible.builtin.include_tasks: ad-hoc.yml
